spring.application.name=redis-demo

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=  # Leave blank if no password
spring.redis.jedis.pool.max-active=10
spring.redis.jedis.pool.max-idle=5
spring.redis.jedis.pool.min-idle=1
spring.redis.jedis.pool.max-wait=-1ms
